[[module.imports]]
path = "github.com/swagger-api/swagger-ui"
ignoreConfig = true
[[module.imports.mounts]]
source = "dist/swagger-ui-bundle.js"
target = "assets/hugomods/swagger-ui/swagger-ui-bundle.js"
[[module.imports.mounts]]
source = "dist/swagger-ui-standalone-preset.js"
target = "assets/hugomods/swagger-ui/swagger-ui-standalone-preset.js"
[[module.imports.mounts]]
source = "dist/swagger-ui.css"
target = "assets/hugomods/swagger-ui/swagger-ui.css"

[params.hugopress.modules.swagger-ui.hooks.head-end]
partial = "hugomods/swagger-ui/assets/css"
cacheable = true
cache_store_key = "hasSwaggerUI"

[params.hugopress.modules.swagger-ui.hooks.body-begin]
partial = "hugomods/swagger-ui/assets/js"
cacheable = true
cache_store_key = "hasSwaggerUI"

[params.swagger_ui]
sass_transpiler = "dartsass"
